-- Add new card detail columns if they don't exist
ALTER TABLE cards 
ADD COLUMN IF NOT EXISTS mana_cost VARCHAR,
ADD COLUMN IF NOT EXISTS type_line VARCHAR,
ADD COLUMN IF NOT EXISTS colors JSON,
ADD COLUMN IF NOT EXISTS cmc FLOAT,
ADD COLUMN IF NOT EXISTS power VARCHAR,
ADD COLUMN IF NOT EXISTS toughness VARCHAR,
ADD COLUMN IF NOT EXISTS oracle_text TEXT,
ADD COLUMN IF NOT EXISTS image_url VARCHAR,
ADD COLUMN IF NOT EXISTS small_image_url VARCHAR,
ADD COLUMN IF NOT EXISTS rarity VARCHAR,
ADD COLUMN IF NOT EXISTS set_code VARCHAR,
ADD COLUMN IF NOT EXISTS set_name VARCHAR,
ADD COLUMN IF NOT EXISTS scryfall_uri VARCHAR;
